{"uuid": "4e1f465b-a763-4491-a55e-c1fd0c789e67", "children": ["281e1794-6363-438a-979f-9d78e535f70f", "d2803511-fbed-4ea6-a4cc-92bc0711f92c"], "befores": [{"name": "init_desktop_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Failed to locate opened application window with appId: Microsoft.WindowsCalculator_8wekyb3d8bbwe!App, and processId: 30508\n\n", "trace": "  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\test_cases\\conftest.py\", line 92, in init_desktop_driver\n    edriver = get_desktop_driver()\n              ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\test_cases\\conftest.py\", line 156, in get_desktop_driver\n    driver = appium.webdriver.Remote(get_data('WinAppDriver_Service'), dc)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 267, in __init__\n    super().__init__(\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 357, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Automation\\pythonProject\\test_automation_final_project\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1709297438271, "stop": 1709549356828}], "start": 1709297438271, "stop": 1709549357454}